import type { Metadata } from "next";
import { Providers } from "./providers";
import "../styles/globals.css";
import { useParams } from "next/navigation";
import { useTranslation } from "@/i18n/client";
import { LocaleTypes } from "@/i18n/settings";

export const metadata: Metadata = {
  title: "ㅁㄴㅇㄹㅁㄴㄹㅁㄴㄹㅁㄴㄹㅁㄴp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}